FROM node:lts-alpine as builder

WORKDIR /usr/src/app

COPY . .

RUN npm install

RUN npm run build


FROM nginx:stable-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /usr/src/app/build /usr/share/nginx/html

EXPOSE 80
