version: "3"

services:
  db:
    image: mongo:3.6.22-xenial
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-app
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.prod
    image: backend:prod
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mern-app
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.prod
    image: frontend:prod
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mern-app
    restart: always

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
